### ISSUE TITLE
Cannot find module 'codesandbox-import-utils/lib/api/define'

### ISSUE THREAD

**Issue by akicho8** [BuptStEve/vuepress-plugin-demo-code#50]
### Steps to reproduce

1. npm i -D vuepress-plugin-demo-code
2. Add 'demo-code' to plugins of `.vuepress/config.js`
3. vuepress dev

### Expected behavior

The demo-code plugin works.

### Actual behavior

Google Chrome Developer Console:

```
utils.js?b143:1 Uncaught Error: Cannot find module 'codesandbox-import-utils/lib/api/define'
    at webpackMissingModule (utils.js?b143:1:1)
    at eval (utils.js?b143:1:1)
    at ../node_modules/vuepress-plugin-demo-code/src/client/utils.js (app.js:5131:1)
    at __webpack_require__ (app.js:833:30)
    at fn (app.js:130:20)
    at eval (cjs.js?!../../../../../opt/nodenv/versions/12.22.0/lib/node_modules/vuepress/node_modules/babel-loader/lib/index.js?!../../../../../opt/nodenv/versions/12.22.0/lib/node_modules/vuepress/node_modules/cache-loader/dist/cjs.js?!../../../../../opt/nodenv/versions/12.22.0/lib/node_modules/vuepress/node_modules/vue-loader/lib/index.js?!../node_modules/vuepress-plugin-demo-code/src/client/OnlineEdit.vue?vue&type=script&lang=js&:5:64)
    at ../../../../../opt/nodenv/versions/12.22.0/lib/node_modules/vuepress/node_modules/cache-loader/dist/cjs.js?!../../../../../opt/nodenv/versions/12.22.0/lib/node_modules/vuepress/node_modules/babel-loader/lib/index.js?!../../../../../opt/nodenv/versions/12.22.0/lib/node_modules/vuepress/node_modules/cache-loader/dist/cjs.js?!../../../../../opt/nodenv/versions/12.22.0/lib/node_modules/vuepress/node_modules/vue-loader/lib/index.js?!../node_modules/vuepress-plugin-demo-code/src/client/OnlineEdit.vue?vue&type=script&lang=js& (app.js:1487:1)
    at __webpack_require__ (app.js:833:30)
    at fn (app.js:130:20)
    at eval (OnlineEdit.vue?79d2:1:1)
```

### System configuration

"vue": "~2.6",
"vue-template-compiler": "~2.6",
"vuepress": "^1.9.8",
"vuepress-plugin-demo-code": "^1.0.0"

node: v12.22.0

vuepress: vuepress/1.9.8 darwin-x64 node-v12.22.0

**Comment by BuptStEve** [comment]
Could you provide a reproduction repo?

**Comment by akicho8** [comment]
Sorry. For some reason, I can no longer reproduce the problem. I will close it for now.
